In [1]:
import tensorflow as tf
print(f"TensorFlow version: {tf.__version__}")

TensorFlow version: 2.2.0


## TensorFlow2
TensorFlow is an open-source, high-performance library for numerical computation that uses directed graphs. Tensoflow can be used for many things, like solving partial diferential equations, and not only machine learning related tasks

A tensor is an N-dimensional array of data: 

<img src="images\tensors.PNG" style="width:500px;height:200px;">

TensorFlow APIs are arranged hierarchically, with the high-level APIs built on the low-level APIs. Machine learning researchers use the low-level APIs to create and explore new machine learning algorithms.

<img src="images\abstractions.PNG" style="width:500px;">



### Lets explore different tensors of various ranks:


<img src="images\different_tensors.PNG" style="width:700px;">

If you are familiary with Numpy, tenosrs behave like numpy n-dimensional arrays except that:
* <font color="green"> tf.constant</font> produces constant tensors
* <font color="green"> tf.Variable </font> produces tenosrs that can be modified

In [2]:
x = tf.constant([[1,2,3],[3,2,1]]) # Constant
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 2, 1]])>

In [6]:
y = tf.Variable([[8,1,2],[6,7,3]]) # Variable
y

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[8, 1, 2],
       [6, 7, 3]])>

In [10]:
# A Variable and a Constant can intereact with each other
x*y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8,  2,  6],
       [18, 14,  3]])>