In [18]:
import tensorflow as tf
import numpy as np
print(f"TensorFlow version: {tf.__version__}")

tf.config.list_physical_devices('GPU')

TensorFlow version: 2.2.0


[]

# More on Variables and constants
Few people make this comparison, but TensorFlow and
Numpy are quite similar. (Both are N-d array libraries!):

* Numpy has Ndarray support, but doesn’t offer methods to
create tensor functions and automatically compute
derivatives (+ no GPU support)

Asaides from that, you can view tensorflow (low-level TF API) as a graph caclualtor, with the advantage that it is only needed to calualte the forward pass, since TF is capable of computing the derrivatives by itself.

Now a little bit of history.  When tensorflow 1.0.0 was relased, you had to create sessions, fill those sessions, and execute them at 
the end. With the introduction of tensorflow 2.0.0, sessions are no longer a thing.  Instead, graps are executed eagerly.

$\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;$
<font color="green"> TF1: How Graphs were built </font> $\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;$ <font color="blue">TF2: How Graphs are built now </font>

```import tensorflow as tf```
$\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;$ 
```import tensorflow as tf```

```x = tf.constant(1)```
$\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;$ 
```x = tf.constant(1)```

```y = tf.constant(2)```
$\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;$ 
```y = tf.constant(2)```

```z = tf.add(x,y)```
$\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;$ 
```z = tf.add(x,y) # The graph runs here```

```with tf.Session() as sess:```

```sess.run(z)```


In [2]:
tf.executing_eagerly() # verify eagerly status 

True

In [39]:
## TF2 does not need a session to run! ##
a = tf.constant(12)  # Define a tensor of rank 0
b = tf.constant(10) # Define a tensor of rank 0
z = tf.add(a,b)     # It runs the "session" eagerly 

print(f"Tpye: {type(z)} \nz:{z}")

Tpye: <class 'tensorflow.python.framework.ops.EagerTensor'> 
z:22


### Introduction to Constants, Tensors, and Variables

Since eager executation is now default, There is no need to create placeholders, as it was needed in TF1, now lets dig deep on TF2:

Tensors in TensorFlow are either contant (tf.constant) or variables (tf.Variable). Constant values can not be changed, while variables values can be.

Both Variables and Constants create a **Tensor** (which can also created directly )

Basic Datatypes:

* tf.float(16,32,64)
* tf.int(8,16,32,64)
* tf.bool

**Initalization**

In [41]:
# We can initalize a value  without specifiyng shape and type
# This initialization applies for Constants and Variables
x = tf.constant(4) # Init a constant
y = tf.Variable(4) # Init a Varibale 
if x == y:         # IF both are the same value/dtype print the value
    print(x) 

tf.Tensor(4, shape=(), dtype=int32)


In [42]:
# Or we can explicitly tell Tensorflow all the information
x = tf.constant(4, shape=(4,4),dtype=tf.float64) # Explcitly tell Tensorflow the initialization
x

<tf.Tensor: shape=(4, 4), dtype=float64, numpy=
array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])>

In [44]:
x = tf.cast(x,dtype=tf.float16) # You can use Cast to change dtype
print(x) 

tf.Tensor(
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]], shape=(4, 4), dtype=float16)


In [45]:
# Broadcasting is also available (like in numpy)
x+1 # adds 1 to all elements of tensor

<tf.Tensor: shape=(4, 4), dtype=float16, numpy=
array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]], dtype=float16)>

In [46]:
# Other Important Constant INitializations:
o = tf.ones((3,3))  # Tensor of ones
z = tf.zeros((2,2)) # Tenosr of zeros
i = tf.eye(3)       # Identity Tensor
r = tf.random.normal((3,3),mean=0, stddev=1) # Random Tensor from distribuiton

print(f"{o}\n\n{z}\n\n{i}\n\n{r}")

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[-0.9726208  -0.01479066 -1.3624561 ]
 [-0.04635035  0.11913349  3.050895  ]
 [-1.93892    -0.26182556  2.2397456 ]]


### Special Methods for Variables
As we said before Tensors in TensorFlow are either contant (tf.constant) or variables (tf.Variable). Constant values can not be changed, while variables values can be.

The main difference is that instances of tf.Variable have methods allowing us to change their values while tensors constructed with tf.constant don't have these methods, and therefore their values can not be changed. When you want to change the value of a tf.Variable x use one of the following method:

* x.assign(new_value)
* x.assign_add(value_to_be_added)
* x.assign_sub(value_to_be_subtracted

In [28]:
x = tf.Variable(2.0, dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>

In [32]:
x.assign(45.8) # Asign a different value of variable
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=45.8>

In [33]:
x.assign_add(4) # Add 4 to current variable
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=49.8>

In [34]:
x.assign_sub(3) # Substract 3 to current value of variable
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=46.8>

### Math operations
#### Element  Wise operations

Tensorflow offers similar point-wise tensor operations as numpy does:

* tf.add allows to add the components of a tensor
* tf.multiply allows us to multiply the components of a tensor
* tf.subtract allow us to substract the components of a tensor
* tf.math.* contains the usual math operations to be applied on the components of a tensor
and many more...

Most of the standard aritmetic operations (tf.add, tf.substrac, etc.) are overloaded by the usual corresponding arithmetic symbols (+, -, etc.)

In [50]:
### Define Tensors ###
A = tf.constant([[1,2,],[1,2,]],shape=(2,2))
B = tf.constant([[1, 2],[3, 4]],shape=(2,2))
### OPERATIONS ####

z = tf.add(A,B)       # Adds two tensors element-wise
z = A + B             # Overloaded form

z = tf.subtract(A,B)  # Substracts two tensors element-wise
z = A - B             # Overloaded form

z = tf.divide(A,B)    # Divides two tensors element-wise
z = A/B               # Overloaded form

z = tf.multiply(A,B)  # Multiplies two tensors element-wise
z = A*B               # Overloaded form

z = A**2              # Raise a tensor element-wise (Overloaded form)
        

#### Matrix multiplication

In [56]:
### Define Tensors ###
A = tf.constant([[1,2,3],[1,2,3]],shape=(2,3))
B = tf.constant([[1, 2,3],[3, 4,4],[1,2,3]],shape=(3,3))
### OPERATIONS ####

Z = tf.matmul(A,B) # Tensor multiplciation
Z = A@B            # Overloaded form
print(f'{Z}')

[[10 16 20]
 [10 16 20]]


### Miscellaneous

In [57]:
### Transpose a Tensor ###
print(A)
AT = tf.transpose(A)
print()
print(AT)

tf.Tensor(
[[1 2 3]
 [1 2 3]], shape=(2, 3), dtype=int32)

tf.Tensor(
[[1 1]
 [2 2]
 [3 3]], shape=(3, 2), dtype=int32)


In [58]:
### Sum Tensor ###
tf.math.reduce_sum(A) # Computes the sum of elements across dimensions of a tensor.

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [59]:
### Dot product ###
tf.tensordot(A,AT,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 14],
       [14, 14]])>

## Tensor Interoperability

In addition to native TF tensors, tensorflow operations can take native python types and NumPy arrays as operands.

In [19]:
# native python list
a_py = [1, 2] 
b_py = [3, 4]
tf.add(a_py, b_py) # TODO 1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

In [20]:
# numpy arrays
a_np = np.array([1, 2])
b_np = np.array([3, 4])
tf.add(a_np, b_np) 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

**Bibliography**
<br>
[MLfromscratch](https://mlfromscratch.com/tensorflow-2)